# Airfield app

# set REDIS_HOST and REDIS_PORT to your local settings

FROM ubuntu:12.04
MAINTAINER Nick Stinemates, Thatcher Peskens
run apt-get update
run apt-get install -y openjdk-7-jdk
run mkdir /work_dir
