#! /bin/bash

echo "debugging Tomcat Web application"

# deploy web application
base_dir="$(cd "$(dirname "$0")"; pwd)"
rm -rf /tomcat/webapps/ROOT
sed -i 's#</Host>#<Context path="" docBase="welcome" /></Host>#g' /tomcat/conf/server.xml
cp $base_dir/welcome/target/welcome*.war /tomcat/webapps/welcome.war

cd /tomcat/bin
./catalina.sh version

# set catalina env as debug mode
touch setenv.sh
echo "export CATALINA_OPTS=\"-agentlib:jdwp=transport=dt_socket,address=8078,server=y,suspend=n\"" >> setenv.sh

# start tomcat
./startup.sh && tail -f /tomcat/logs/catalina.out
