# Airfield app

# set REDIS_HOST and REDIS_PORT to your local settings

FROM 9.181.27.216/tomcat7image
MAINTAINER HaiRui Zhang, Kai Zhang
expose 8080
cmd ["/bin/bash", "/work_dir/run_app"]
add ./welcome /work_dir

